inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'pkg/**/*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.2

Metrics/BlockLength:
  Exclude:
    - 'spec/defines/service_spec.rb'
  ExcludedMethods:
    - 'describe'
    - 'context'
    - 'it'
    - 'shared_examples'
    - 'newtype'
    - 'provide'
    - 'newproperty'
    - 'let'
    - 'shell'
    - 'CentOS'

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

# Disabled undesired features
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%r': '||'
