# Configure options
Metrics/AbcSize:
  Max: 50

Metrics/ClassLength:
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 20

# Disabled undesired features
Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%r': '||'

Style/PerlBackrefs:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/WordArray:
  Enabled: false
