node 'agent' {
  File { backup => false, owner => 'aem', group => 'aem' }

  aem::agent::replication { 'Agent Title':
    agent_user            => 'agentuser',
    batch_enabled         => true,
    batch_max_wait        => 60,
    batch_trigger_size    => 100,
    description           => 'Custom Description',
    enabled               => false,
    home                  => '/opt/aem/author',
    log_level             => 'debug',
    mixin_types           => ['cq:ReplicationStatus'],
    name                  => 'customname',
    password              => 'admin',
    protocol_close_conn   => true,
    protocol_conn_timeout => 1000,
    protocol_http_headers => ['CQ-Action:{action}', 'CQ-Handle:{path}', 'CQ-Path:{path}'],
    protocol_http_method  => 'POST',
    protocol_interface    => '127.0.0.1',
    protocol_sock_timeout => 1000,
    protocol_version      => 1.0,
    proxy_host            => 'proxy.domain.com',
    proxy_ntlm_domain     => 'proxydomain',
    proxy_ntlm_host       => 'proxy.ntlm.domain.com',
    proxy_password        => 'proxypassword',
    proxy_port            => 12345,
    proxy_user            => 'proxyuser',
    resource_type         => 'cq/replication/components/revagent',
    retry_delay           => 60,
    reverse               => true,
    runmode               => 'author',
    serialize_type        => 'flush',
    static_directory      => '/var/path',
    static_definition     => '/content/geo* ${path}.html?wcmmode=preview',
    template              => '/libs/cq/replication/templates/revagent',
    timeout               => 120,
    trans_allow_exp_cert  => true,
    trans_ntlm_domain     => 'transdomain',
    trans_ntlm_host       => 'trans.ntlm.domain.com',
    trans_password        => 'transpassword',
    trans_ssl             => 'relaxed',
    trans_uri             => 'http://localhost:4503/bin/receive?sling:authRequestLogin=1',
    trans_user            => 'transuser',
    trigger_ignore_def    => true,
    trigger_no_status     => false,
    trigger_no_version    => true,
    trigger_on_dist       => true,
    trigger_on_mod        => true,
    trigger_on_receive    => true,
    trigger_onoff_time    => true,
    username              => 'admin'
  }
}